name: firestore_figure_saver
description: Save on firestore all the figure drawn by user
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.0-374.0.dev <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  grapher_user_draw:
    path: ../grapher_user_draw
  flutter:
    sdk: flutter
  cloud_firestore: ^4.3.0
  firebase_core: ^2.4.0
  logging: ">1.0.0 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ">=0.3.0 <1.0.0"
  fake_cloud_firestore: ^2.1.0
